import { Command, CommandContext, CommandDependencies } from './types';
import { commandUtils, isSendableChannel } from './utils';
import { SYS_PREFIX } from './constants';

const VIDEO_ID_RE = /^[A-Za-z0-9_-]{11}$/;
const FETCH_TIMEOUT_MS = 60_000;

export function extractVideoId(input: string): string | null {
    if (VIDEO_ID_RE.test(input)) return input;

    let url: URL;
    try {
        url = new URL(input);
    } catch {
        return null;
    }

    const host = url.hostname.replace(/^www\.|^m\.|^music\./, '');
    let id: string | null = null;

    if (host === 'youtu.be') {
        id = url.pathname.split('/')[1] || null;
    } else if (host === 'youtube.com') {
        const pathMatch = url.pathname.match(/^\/(?:shorts|embed|live)\/([^/?]+)/);
        id = url.searchParams.get('v') || pathMatch?.[1] || null;
    }

    return id && VIDEO_ID_RE.test(id) ? id : null;
}

// The service returns markdown: "# Transcript: <title>", metadata lines,
// "## Transcript" with the [m:ss] text, then a "---" promo footer.
export function parseTranscriptPage(body: string): { title: string | null; text: string } {
    const title = body.match(/^# Transcript: (.+)$/m)?.[1]?.trim() || null;

    let text = body;
    const sectionStart = body.indexOf('## Transcript');
    if (sectionStart !== -1) {
        text = body.slice(sectionStart + '## Transcript'.length);
    }
    const footerStart = text.lastIndexOf('\n---\n');
    if (footerStart !== -1 && text.slice(footerStart).includes('Generated by')) {
        text = text.slice(0, footerStart);
    }
    return { title, text: text.trim() };
}

export const transcribeCommand: Command = {
    names: ['transcribe'],
    description: 'Fetch the transcript of a YouTube video.',
    category: 'Transcription',
    options: [{ name: 'url', description: 'YouTube URL (or video ID) to transcribe', type: 'string', required: true }],
    deferred: true,
    async execute(ctx: CommandContext, deps: CommandDependencies) {
        const input = ctx.args[0];
        if (!input) {
            await commandUtils.reply(ctx.message, 'Usage: `!transcribe <youtube-url>`');
            return;
        }

        const channel = ctx.message.channel;
        if (!isSendableChannel(channel)) return;

        const videoId = extractVideoId(input);
        if (!videoId) {
            await commandUtils.replyError(ctx.message, 'Could not find a YouTube video ID in that input. `!transcribe` supports YouTube links only.');
            return;
        }

        await commandUtils.reply(ctx.message, 'Fetching transcript...');
        await channel.sendTyping();

        try {
            const res = await fetch(`https://youtube-transcript.ai/transcript/${videoId}.txt`, {
                signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
            });
            const body = await res.text();

            if (!res.ok) {
                // 404 body is markdown with a "Reason: {...}" line.
                const reason = body.match(/^Reason: (.+)$/m)?.[1] || `service returned HTTP ${res.status}`;
                await commandUtils.replyError(ctx.message, `No transcript available: ${reason}`);
                return;
            }

            const { title, text } = parseTranscriptPage(body);
            if (!text.length) {
                await commandUtils.replyError(ctx.message, 'Transcript came back empty.');
                return;
            }

            await channel.send(`${SYS_PREFIX}Transcription${title ? ` of **${title}**` : ''}:`);
            const chunks = commandUtils.splitMessageIntoChunks([{ role: 'user', content: text }]);
            for (const chunk of chunks) {
                if (chunk) await channel.send(chunk);
            }
        } catch (error: any) {
            console.error('Transcribe command error:', error);
            await commandUtils.replyError(ctx.message, `Transcription failed: ${error.message}`);
        }
    }
};

export const transcribeCommands: Command[] = [transcribeCommand];
