import { extractVideoId, parseTranscriptPage, collapseRepeatedPhrases } from './transcribe';

describe('collapseRepeatedPhrases', () => {
  it('collapses a doubled phrase', () => {
    expect(collapseRepeatedPhrases('Hey everyone, it\'s Ross from the Hey everyone, it\'s Ross from the Otherworld'))
      .toBe('Hey everyone, it\'s Ross from the Otherworld');
  });

  it('collapses a tripled phrase', () => {
    expect(collapseRepeatedPhrases('Are there rules? Are there rules? Are there rules? Is that a misnomer?'))
      .toBe('Are there rules? Is that a misnomer?');
  });

  it('collapses single-word echoes', () => {
    expect(collapseRepeatedPhrases('where will you get the answer? answer? answer? Is it in the book?'))
      .toBe('where will you get the answer? Is it in the book?');
  });

  it('preserves punctuation-differentiated repetition', () => {
    expect(collapseRepeatedPhrases('no, no, no! I said so.')).toBe('no, no, no! I said so.');
  });

  it('strips timestamps so repeats spanning block boundaries collapse', () => {
    expect(collapseRepeatedPhrases('especially if it\'s original Dungeons and Dragons, [1:17] it\'s original Dungeons and Dragons, it\'s original Dungeons and Dragons, which is so genius'))
      .toBe('especially if it\'s original Dungeons and Dragons, which is so genius');
  });

  it('collapses nested overlaps longest-run-first', () => {
    expect(collapseRepeatedPhrases('a b c a b c a b c d')).toBe('a b c d');
  });
});

describe('extractVideoId', () => {
  it('extracts from standard watch URLs', () => {
    expect(extractVideoId('https://www.youtube.com/watch?v=dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://youtube.com/watch?v=dQw4w9WgXcQ&t=42s')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://m.youtube.com/watch?v=dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://music.youtube.com/watch?v=dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('extracts from short and embed URL forms', () => {
    expect(extractVideoId('https://youtu.be/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://youtu.be/dQw4w9WgXcQ?t=10')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://www.youtube.com/shorts/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://www.youtube.com/embed/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://www.youtube.com/live/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('accepts a bare video ID', () => {
    expect(extractVideoId('dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('rejects non-YouTube URLs and malformed input', () => {
    expect(extractVideoId('https://vimeo.com/12345')).toBeNull();
    expect(extractVideoId('https://example.com/watch?v=dQw4w9WgXcQ')).toBeNull();
    expect(extractVideoId('not a url')).toBeNull();
    expect(extractVideoId('https://youtube.com/watch?v=tooshort')).toBeNull();
    expect(extractVideoId('https://youtube.com/watch')).toBeNull();
  });
});

describe('parseTranscriptPage', () => {
  const page = [
    '# Transcript: Some Video Title',
    '',
    'Source video: https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Language: en · Duration: 3:27 · Words: 481',
    '',
    '## Transcript',
    '[0:01] Hello there.',
    '',
    '[0:31] General Kenobi.',
    '---',
    'Generated by https://youtube-transcript.ai — free YouTube transcript & summary extractor.',
  ].join('\n');

  it('extracts title and transcript body, stripping metadata and footer', () => {
    const { title, text, autoGenerated } = parseTranscriptPage(page);
    expect(title).toBe('Some Video Title');
    expect(autoGenerated).toBe(false);
    expect(text).toContain('[0:01] Hello there.');
    expect(text).toContain('[0:31] General Kenobi.');
    expect(text).not.toContain('Source video');
    expect(text).not.toContain('Generated by');
  });

  it('keeps deliberate repetition in manual transcripts', () => {
    const manual = page.replace('[0:01] Hello there.', '[0:01] Never gonna give, never gonna give,');
    const { text, autoGenerated } = parseTranscriptPage(manual);
    expect(autoGenerated).toBe(false);
    expect(text).toContain('Never gonna give, never gonna give,');
  });

  it('dedupes rolling-caption repeats in auto-generated transcripts', () => {
    const auto = page
      .replace('Language: en ·', 'Language: English (auto-generated) ·')
      .replace('[0:01] Hello there.', '[0:01] Hello there. Hello there. Hello there.');
    const { text, autoGenerated } = parseTranscriptPage(auto);
    expect(autoGenerated).toBe(true);
    expect(text).toContain('Hello there. General Kenobi.');
    expect(text).not.toContain('Hello there. Hello there.');
    expect(text).not.toContain('[0:01]');
  });

  it('falls back to the whole body when headings are missing', () => {
    const { title, text } = parseTranscriptPage('just some text');
    expect(title).toBeNull();
    expect(text).toBe('just some text');
  });
});
