import { extractVideoId, parseTranscriptPage } from './transcribe';

describe('extractVideoId', () => {
  it('extracts from standard watch URLs', () => {
    expect(extractVideoId('https://www.youtube.com/watch?v=dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://youtube.com/watch?v=dQw4w9WgXcQ&t=42s')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://m.youtube.com/watch?v=dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://music.youtube.com/watch?v=dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('extracts from short and embed URL forms', () => {
    expect(extractVideoId('https://youtu.be/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://youtu.be/dQw4w9WgXcQ?t=10')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://www.youtube.com/shorts/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://www.youtube.com/embed/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://www.youtube.com/live/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('accepts a bare video ID', () => {
    expect(extractVideoId('dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  it('rejects non-YouTube URLs and malformed input', () => {
    expect(extractVideoId('https://vimeo.com/12345')).toBeNull();
    expect(extractVideoId('https://example.com/watch?v=dQw4w9WgXcQ')).toBeNull();
    expect(extractVideoId('not a url')).toBeNull();
    expect(extractVideoId('https://youtube.com/watch?v=tooshort')).toBeNull();
    expect(extractVideoId('https://youtube.com/watch')).toBeNull();
  });
});

describe('parseTranscriptPage', () => {
  const page = [
    '# Transcript: Some Video Title',
    '',
    'Source video: https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    'Language: en · Duration: 3:27 · Words: 481',
    '',
    '## Transcript',
    '[0:01] Hello there.',
    '',
    '[0:31] General Kenobi.',
    '---',
    'Generated by https://youtube-transcript.ai — free YouTube transcript & summary extractor.',
  ].join('\n');

  it('extracts title and transcript body, stripping metadata and footer', () => {
    const { title, text } = parseTranscriptPage(page);
    expect(title).toBe('Some Video Title');
    expect(text).toContain('[0:01] Hello there.');
    expect(text).toContain('[0:31] General Kenobi.');
    expect(text).not.toContain('Source video');
    expect(text).not.toContain('Generated by');
  });

  it('falls back to the whole body when headings are missing', () => {
    const { title, text } = parseTranscriptPage('just some text');
    expect(title).toBeNull();
    expect(text).toBe('just some text');
  });
});
