import { Command, CommandContext, CommandDependencies } from './types';
import { commandUtils, isSendableChannel } from './utils';
import { SYS_PREFIX } from './constants';

const VIDEO_ID_RE = /^[A-Za-z0-9_-]{11}$/;
const FETCH_TIMEOUT_MS = 60_000;

export function extractVideoId(input: string): string | null {
    if (VIDEO_ID_RE.test(input)) return input;

    let url: URL;
    try {
        url = new URL(input);
    } catch {
        return null;
    }

    const host = url.hostname.replace(/^www\.|^m\.|^music\./, '');
    let id: string | null = null;

    if (host === 'youtu.be') {
        id = url.pathname.split('/')[1] || null;
    } else if (host === 'youtube.com') {
        const pathMatch = url.pathname.match(/^\/(?:shorts|embed|live)\/([^/?]+)/);
        id = url.searchParams.get('v') || pathMatch?.[1] || null;
    }

    return id && VIDEO_ID_RE.test(id) ? id : null;
}

// YouTube auto-captions render as a rolling window, so each caption line
// appears in 2-3 consecutive cues and the transcript service flattens them
// without deduping. Collapse immediate exact word-run repeats, longest run
// first; staying in place after a cut catches lines repeated three times.
// Comparison is exact (punctuation-sensitive), so deliberate speech like
// "no, no, no" survives. Timestamps are stripped first because repeats span
// the [m:ss] block boundaries.
const TIMESTAMP_RE = /\[\d+:\d{2}(?::\d{2})?\]/g;
const MAX_PHRASE_WORDS = 20;

export function collapseRepeatedPhrases(text: string): string {
    const words = text.replace(TIMESTAMP_RE, ' ').split(/\s+/).filter(Boolean);
    let i = 0;
    while (i < words.length) {
        let cut = false;
        for (let n = MAX_PHRASE_WORDS; n >= 2; n--) {
            if (i + 2 * n > words.length) continue;
            let eq = true;
            for (let k = 0; k < n; k++) {
                if (words[i + k] !== words[i + n + k]) { eq = false; break; }
            }
            if (eq) { words.splice(i + n, n); cut = true; break; }
        }
        // A doubled single word is often deliberate speech ("no, no!" has an
        // identical "no," pair); only a run of three or more is the artifact.
        if (!cut) {
            let run = 1;
            while (i + run < words.length && words[i + run] === words[i]) run++;
            if (run >= 3) { words.splice(i + 1, run - 1); cut = true; }
        }
        if (!cut) i++;
    }
    return words.join(' ');
}

// The service returns markdown: "# Transcript: <title>", metadata lines,
// "## Transcript" with the [m:ss] text, then a "---" promo footer.
export function parseTranscriptPage(body: string): { title: string | null; text: string; autoGenerated: boolean } {
    const title = body.match(/^# Transcript: (.+)$/m)?.[1]?.trim() || null;
    const autoGenerated = /^Language: [^\n]*auto-generated/m.test(body);

    let text = body;
    const sectionStart = body.indexOf('## Transcript');
    if (sectionStart !== -1) {
        text = body.slice(sectionStart + '## Transcript'.length);
    }
    const footerStart = text.lastIndexOf('\n---\n');
    if (footerStart !== -1 && text.slice(footerStart).includes('Generated by')) {
        text = text.slice(0, footerStart);
    }
    text = text.trim();
    // Manual transcripts keep their timestamps and any deliberate repetition
    // (e.g. song choruses); only auto-generated ones need the dedup pass.
    if (autoGenerated) {
        text = collapseRepeatedPhrases(text);
    }
    return { title, text, autoGenerated };
}

export const transcribeCommand: Command = {
    names: ['transcribe'],
    description: 'Fetch the transcript of a YouTube video.',
    category: 'Transcription',
    options: [{ name: 'url', description: 'YouTube URL (or video ID) to transcribe', type: 'string', required: true }],
    deferred: true,
    async execute(ctx: CommandContext, deps: CommandDependencies) {
        const input = ctx.args[0];
        if (!input) {
            await commandUtils.reply(ctx.message, 'Usage: `!transcribe <youtube-url>`');
            return;
        }

        const channel = ctx.message.channel;
        if (!isSendableChannel(channel)) return;

        const videoId = extractVideoId(input);
        if (!videoId) {
            await commandUtils.replyError(ctx.message, 'Could not find a YouTube video ID in that input. `!transcribe` supports YouTube links only.');
            return;
        }

        await commandUtils.reply(ctx.message, 'Fetching transcript...');
        await channel.sendTyping();

        try {
            const res = await fetch(`https://youtube-transcript.ai/transcript/${videoId}.txt`, {
                signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
            });
            const body = await res.text();

            if (!res.ok) {
                // 404 body is markdown with a "Reason: {...}" line.
                const reason = body.match(/^Reason: (.+)$/m)?.[1] || `service returned HTTP ${res.status}`;
                await commandUtils.replyError(ctx.message, `No transcript available: ${reason}`);
                return;
            }

            const { title, text } = parseTranscriptPage(body);
            if (!text.length) {
                await commandUtils.replyError(ctx.message, 'Transcript came back empty.');
                return;
            }

            await channel.send(`${SYS_PREFIX}Transcription${title ? ` of **${title}**` : ''}:`);
            const chunks = commandUtils.splitMessageIntoChunks([{ role: 'user', content: text }]);
            for (const chunk of chunks) {
                if (chunk) await channel.send(chunk);
            }
        } catch (error: any) {
            console.error('Transcribe command error:', error);
            await commandUtils.replyError(ctx.message, `Transcription failed: ${error.message}`);
        }
    }
};

export const transcribeCommands: Command[] = [transcribeCommand];
